
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/
export const USER_ROLE = {
  User: 'User',
  Admin: 'Admin'
} as const

export type USER_ROLE = (typeof USER_ROLE)[keyof typeof USER_ROLE]
